# Generated by Django 5.1.6 on 2025-02-26 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='user',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product'),
        ),
    ]
